language: ruby
rvm:
- ruby-head
deploy:
  provider: heroku
  app: gentle-everglades-44932
  api_key:
    secure: JDTmMxSPwbY+64SbAnWm5D++iRCWaS85Yo64SVgTlDZCGWLSjJW2W4xRpLtfYe5Q2mWDJ7GxUag6MkgwtFg2OUeYHs2ApCyHMZEZVYjm3srd7HBYXaCdx9JMpr8+GC1MtYRsPss2ZbdlBKKLItW1Q9qAAiaOSA+jPDpkEt3vZMzzCRAEDkPYtfqr4sjSAr7mTNy4qS2TTvR5Wewzy//vJFNrUZPon+M1ZNgdm79wowhO6K1B5taSrRH6D2SNgqVwu4/FKh8itoRI+ea+tJH40QjNTqvyYh8rHTOsGsISYovumxyxCIUSln1nWdsQR/EoTPQFYkXSH1WT1EefIeeuKJvbI1Z1d6nmf3RpcaDEP+9yDPZ3nGVvV9w8TKKyyGqG+wyfn8+Z195xyMB3SIqi9sdgWOZhUts4RQ5AzySfmAfJP/E9S22B1vbejLQIu4PRCpWr7zN9bRV66EfhnORUNQO/JWRF8DEfgraGuSpcnh9dn0D8M2CuB9uukDLuDTcQhS7cojGnqclno+hhbR77H2jNIJX1UJa7aFXzv78uE+1zbV8VHgCevIVglb50CUQB1c5oEYjG54DgSfkJRtg14ApUXbqwZCIgknuTvOIfx+nGlZZS27ungY2x5MPASEdKlIJLOVt55211f4yY3DRw2QrCwUg9HXFWPBfEv1QKtUQ=
