# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 541f1acaff5233d4444e8e26ebac65f64b9f0f792c70fa0ee5801b3dbfd02f8bac3554b98d9eaf298559627c5b654991ea703b013c1537860218e7cfc0562b2b

test:
  secret_key_base: 021318d9af49a55e5a8c6c6aae069c7453b9b0f2d21d63fe96bcce3315d970092461ac202e302211d15c8d9fd6bb88b07b07a63e21f33c5b49da67ba827bfa9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
